/**
 * PaymentReceiver is a class which is responsible for making plugins to receive payments
 * @class PaymentReceiver
 */
export class PaymentReceiver {
    /**
     * @constructor PaymentReceiver
     * @param {DB} db - instance of a database
     * @param {PluginManager} pluginManager - instance of a plugin manager
     * @param {RemoteStorage} storage - instance of a local storage (e.g. HyperDrive)
     * @param {Function} notificationCallback - callback which is called when payment is received
     */
    constructor(db: DB, pluginManager: PluginManager, storage: RemoteStorage, notificationCallback: Function);
    db: DB;
    storage: RemoteStorage;
    notificationCallback: Function;
    pluginManager: PluginManager;
    ready: boolean;
    /**
     * Initialize, get ready to receive payments at returned URL
     * @param {PaymentAmount} [amount] - amount of money to receive
     * @returns {Promise<String>} - url to local drive where slashpay.json file is located
     */
    init(): Promise<string>;
    /**
     * Create private payment endpoints which are encrypted
     * @param {string} clientOrderId - invoice clientOrderId
     * @param {PaymentAmount} expectedAmount - expectedAmount of money to receive
     * @returns {Promise<String>} - url to local drive where slashpay.json file is located
    */
    createInvoice(clientOrderId: string, expectedAmount: PaymentAmount): Promise<string>;
    /**
     * Sotres payload (generated by plugin) data in to file
     * @param {Object} payload - payload to receive payment
     */
    createPaymentFile(payload: any, path?: string): Promise<void>;
    /**
     * Callback which is called by plugin when payment is received
     * @param {Object} payload - payment object
     * @returns {Promise<void>}
     */
    handleNewPayment(payload: any, regenerateSlashpay?: boolean): Promise<void>;
    updatePayment(payload: any): Promise<{
        paymentObject: any;
        missingAmount: PaymentAmount;
    }>;
    createPayment(payload: any, initial?: boolean): Promise<PaymentIncoming>;
    /**
     * @method generateSlashpayContent
     * @param {Array<String>} paymentPluginNames - list of payment plugin names
     * @param {string} [clientOrderId] - id of invoice
     * @returns {Object} - content of slashpay.json file
     */
    generateSlashpayContent(paymentPluginNames: Array<string>, clientOrderId?: string): any;
    getUrlParams(name: any, clientOrderId: any): (string | {
        encrypt: boolean;
    })[];
    /**
     * @method getListOfSupportedPaymentMethods
     * @returns {Array<String>} - list of payment plugin names
     */
    getListOfSupportedPaymentMethods(): Array<string>;
}
export namespace ERRORS {
    const PAYMENT_RECEIVER_NOT_READY: string;
    const PAYLOAD_CLIENT_ORDER_ID_IS_MISSING: string;
    const PAYMENT_OBJECT_NOT_FOUND: string;
}
import { PaymentAmount } from "./PaymentAmount";
import { PaymentIncoming } from "./PaymentIncoming";
